name: Build and Push to DockerHub

on:
  push:
    branches:
      - main  # triggers on push to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/crud-api:latest .

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/crud-api:latest

    - name: Send Success Mail
      if: success()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: Docker Build Succeeded 🎉
        to: ${{ secrets.MAIL_RECEIVER }}
        from: GitHub CI <${{ secrets.MAIL_USERNAME }}>
        body: |
          ✅ Docker image for CRUD API has been built and pushed successfully to Docker Hub.

    - name: Send Failure Mail
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: Docker Build Failed ❌
        to: ${{ secrets.MAIL_RECEIVER }}
        from: GitHub CI <${{ secrets.MAIL_USERNAME }}>
        body: |
          ❌ Docker image build or push FAILED.
          Please check the GitHub Actions log for more details...
